Remove unused secrets

diff --git a/.github/workflows/inventory-and-detection.yml b/.github/workflows/inventory-and-detection.yml
--- a/.github/workflows/inventory-and-detection.yml
+++ b/.github/workflows/inventory-and-detection.yml
@@ -10,10 +10,6 @@ on:
     branches: ['**']
 
 env:
-  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
-  CODEARTIFACT_REGISTRY: ${{ secrets.CODEARTIFACT_REGISTRY }}
-  CODEARTIFACT_SCOPE: ${{ secrets.CODEARTIFACT_SCOPE }}
-  CODEARTIFACT_TOKEN: ${{ secrets.CODEARTIFACT_TOKEN }}
   INVENTORY_REPO_PAT: ${{ secrets.INVENTORY_REPO_PAT }}
   NPMRC: ${{ secrets.NPMRC_RO_FILE }}
 
@@ -28,6 +24,19 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+
+      - name: Configure git for inventory and detection
+        run: |
+          [ -n "${INVENTORY_REPO_PAT:-}" ] || { echo "INVENTORY_REPO_PAT is empty"; exit 1; }
+
+      - name: Configure npm auth for both registries
+        run: |
+          set -euo pipefail
+
+          # Safety checks so you fail fast if secrets are missing
+          [ -n "${NPMRC:-}" ] || { echo "NPMRC env variable is empty, make sure the NPMRC_RO_FILE secret is set"; exit 1; }
+
+          echo "$NPMRC" > $HOME/.npmrc
 
       - name: Install Chrome dependencies
         run: |
@@ -71,24 +80,11 @@ jobs:
             wget \
             xdg-utils
 
-      - name: Configure git for inventory and detection
-        run: |
-          [ -n "${INVENTORY_REPO_PAT:-}" ] || { echo "INVENTORY_REPO_PAT is empty"; exit 1; }
-
       - name: Use Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v4
         with:
           node-version: ${{ matrix.node-version }}
           cache: 'npm'
-
-      - name: Configure npm auth for both registries
-        run: |
-          set -euo pipefail
-
-          # Safety checks so you fail fast if secrets are missing
-          [ -n "${NPMRC:-}" ] || { echo "NPMRC env variable is empty, make sure the NPMRC_RO_FILE secret is set"; exit 1; }
-
-          echo "$NPMRC" > $HOME/.npmrc
 
       - name: Install dependencies
         run: |
